### ISSUE TITLE
RFC - tiny cheats

### ISSUE THREAD

**Issue by spences10** [spences10/cheat-sheets#14]
This is to discuss how the sheets are broken up (if at all) to cater for the UI aspect of presenting the user with a flash card.

My usual usage for these sheets is:

Navigate to the repo
Navigate to the desired section, usually, git
Ctrl+f for finding what I'm looking for

Once the search function is enabled and we understand the functionality then I think we can re-visit this issue.

**Comment by jsjoeio** [comment]
Okay so let's think...

Since the whole purpose is to navigate to a specific cheat sheet, we probably want the landing page to have the search. Then I imagine, you search for the desired section (i.e. git). 

It will bring you to the section page, and then you can search there as well.

For search, we can use [Downshift](https://github.com/paypal/downshift). Built by Kent and it was pretty easy to implement on a piece of software at our company so it should work seamlessly with Gatsby.
